### ISSUE TITLE
Any plans for OData contains, startswith, endswith?

### ISSUE THREAD

**Issue by talismax** [JocaPC/sql-server-rest-api#2]

**Comment by jovanpop-msft** [comment]
This is a good question - currently, it is partially supported. Whenever someone sends a query with unsupported functions such as contains, indexof, startswith, or endwith in OData Url, service will send the query that uses user-defined functions with the same name in odata schema: 
- odata.contains(...)
- odata.indexof(...)
- odata.startswith(....)
- odata.endswith(....)

These UDFs will use the same signature as OData functions (you can see the queries in the trace/profiler). You can create your user-defined functions in odata schema that wrap T-SQL functions and it should work. Maybe in the future I will support it natively, but it is tricky to translate these functions to T-SQL queries in this case.

Let me know does it work for you.
