### ISSUE TITLE
ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by Jass7** [JocaPC/sql-server-rest-api#7]
Hello Jovan,
First thanks for this great work. 
I am trying to implement this project but getting some notnullexception... I don't have null values in my columns, and connection string is set properly per your instructions. Here is the exception:

"
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null.
Parameter name: Connection string is not set.
Belgrade.SqlClient.Common.GenericCommand..ctor(DbConnection connection)

Stack Query Cookies Headers
ArgumentNullException: Value cannot be null.
 Parameter name: Connection string is not set.
Belgrade.SqlClient.Common.GenericCommand..ctor(DbConnection connection)
MsSql.RestApi.StartUp.CreateCommand(Option options, IServiceProvider sp) in StartUp.cs
-
                }
            }
            return pipe;
        }
        private static ICommand CreateCommand(Option options, IServiceProvider sp)
        {
            var cmd = new Command(new SqlConnection(options.ConnString));
            var logger = TryGetLogger<QueryPipe>(sp);
            if (logger != null)
                cmd.AddLogger(logger);
            if (options.SessionContext != null && options.SessionContext.Count >= 1)
            {
MsSql.RestApi.StartUp+<>c__DisplayClass1_0.<AddSqlClient>b__2(IServiceProvider sp) in StartUp.cs
-
            init(options);
            switch (options.ServiceScope)
            {
                case Option.ServiceScopeEnum.SCOPED:
 
"
Can you please advise what I should do to solve this problem. Just to mention, I did basic settings without experimenting and creating a simple database with fields defined in your project, all tables are filled with values. Only I am not sure does Sales should also be a created table in dB with columns CustomerId, OrderID, InvoiceID?
Thanks in advance
Best regards
Jasmina

**Comment by JocaPC** [comment]
Hi Jasmina,

At the first look it seems to me that you haven't provided connection string to RestApi or you are somehow providing SqlConnection without set connection string. The exception is thrown here: 

https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Code/Common/GenericCommand.cs#L30

Could you run your code that initializes RestApi it in debugger and check is there are connection string value in the code that you are calling. My first guess is that some code didn't read the value from some config file.

**Comment by Jass7** [comment]
Hi Jovan, 
Thanks a lot for a prompt response, now it seems I can establish a connection to the server but  I am getting the following message :
{"code":208,"message":{"lang":"en","value":"Invalid object name 'Application.People'.","innererror":null}}
In my database, I made the schema named Application and also I do have all tables with exact names and names of columns. All of them are granted to public (please take a look at 2 print-screens in attachment).
Sorry that I came up with a new question. 
Best regards,
Jasmina
![screen shot 2018-10-25 at 21 16 07](https://user-images.githubusercontent.com/17203405/47524523-22318000-d89b-11e8-966d-b36105f3553c.png)

![screen shot 2018-10-25 at 20 36 36](https://user-images.githubusercontent.com/17203405/47522654-68d0ab80-d896-11e8-8687-5c4ea8ea5886.png)

**Comment by JocaPC** [comment]
You need to put tables in Application schema and not in dbo schema, or put "dbo.Invoices" instead of "Application.Invoices". Maybe you can use other constructor new TableSpec(schema:"dbo", table:"Invoices"). See examples here: https://github.com/Microsoft/sql-server-samples/tree/master/samples/databases/wide-world-importers/wwi-app/Controllers

Note that I just published the latest code in different nuget package MsSql.RestApi instead of old SQL-Server-Rest-Api.

**Comment by Jass7** [comment]
Thanks a lot Jovan, not it works fine. :)
